### ISSUE TITLE
Repeating events on calendar do not repeat on org side

### ISSUE THREAD

**Issue by af00b22f-4fd1-42c0-ba3f-a74ec02e08d0** [dengste/org-caldav#278] opened 2023-09-13 14:40 UTC
I have a lot of weekly and monthly events in my Nextcloud calendar.
On the org side they appear as one-off events, unfortunately.

**Comment by gardebreak** [comment] 2023-09-13 23:17
I have the same issue. Even when I create events with a repeating timestamp in org and sync them to Nextcloud, at some point they sync back from Nextcloud and the repeating timestamp in org is removed. They remain repeating in the Nextcloud calendar.

**Comment by af00b22f-4fd1-42c0-ba3f-a74ec02e08d0** [comment] 2023-09-14 09:31
I see, that this problem is mentioned in `README.org`, but I didn't find the corresponding issue.

Unfortunately, this is a dealbreaker for me, because I have multiple recurring events originating from my calendar. And my elisp (and org and caldav) knowledge is far too limited to do something about it.

**Comment by jackkamm** [comment] 2023-09-25 02:50
Duplicate of https://github.com/dengste/org-caldav/issues/150

**Comment by jackkamm** [comment] 2024-09-08 22:54
Fixed by https://github.com/dengste/org-caldav/pull/308

**Closed by jackkamm** 2024-09-08 22:54 UTC
